### ISSUE TITLE
class-like syntax

### ISSUE THREAD

**Issue by vjpr** [WebReflection/universal-mixin#3]
Is it possible to use classes to define the mixins instead of objects? I think it would look nicer...

``` js
class MyMixin {
  static a = 'a'
  b = 'b'
  init() {
  }
  static foo() { }
  bar() { }
}
```

**Comment by WebReflection** [comment]
classes involve constructors, which is not a good idea for mixins.
It might be worth exploring the usage of classes just for one reason: statics, otherwise not possible to define to the target.

However, this module works with objects too, where there's no difference between own properties and static properties so ... as it is, I'm not sure this is a good, portable, idea.

Do you have any example on how this work or why this is better, beside some missing comma between literal object and class declaration?

**Comment by vjpr** [comment]
> Do you have any example on how this work or why this is better, beside some missing comma between literal object and class declaration?

It's just a nicer looking syntax. Generally I start building a class with ES6 class syntax, then I find I want to split of some methods into a mixin. So its strange having to move from ES6 idomatic classes, to a custom `mixin({}, {})` signature. 

Also, easier for code editor tooling, and flow type annotations which have mixin support.

**Comment by WebReflection** [comment]
Doing some gardening. It is not possible to use a class as decorator, since classes need `new` invocation. As it is, your proposal doesn't fit for mixins usage.
