### ISSUE TITLE
mixin ovveride ES6 class method

### ISSUE THREAD

**Issue by dredzone** [WebReflection/universal-mixin#6]
If class A has method test and mixin has function with the same name as class method definition replaced by mixin function, is that intended? I was expecting existing methods given priority over mixin functions.

**Comment by WebReflection** [comment]
A missing method can break both mixin and class. Priority doesn't solve the
conflict and I believe it's developer responsibility to avoid properties
and methods name clashes.

Maybe giving class priority makes more sense than giving it to a mixin but
as it is now there's no way to eventually reach, and manually invoke, a
mixin method. It's also true that a mixin method should never invoke a
generic class one. TL;DR I'll think about it, not entirely sure what's the
best way to workaround conflicts instead of throwing.

**Comment by WebReflection** [comment]
Major bump `v2.0.0` avoids overloads and exposes **only methods** through mixins.

```js
const M = mixin({
  method() {
    this.m = true;
  }
});

@M
class A {
  method() {
    M.method.call(this);
    this.a = true;
  }
}

const a = new A;
a.method();
a.a; // true
a.m; // true
```
